from typing import Any, Optional

def add_metaclass(metaclass: Any): ...
def indent(text: Any, prefix: Any, predicate: Optional[Any] = ...): ...
def deprecated_func(func: Any): ...
def byte2int(x: Any): ...
