from .wasmtypes import *
from .types import RepeatField as RepeatField, Structure as Structure
from typing import Any

class BlockImm(Structure):
    sig: Any = ...

class BranchImm(Structure):
    relative_depth: Any = ...

class BranchTableImm(Structure):
    target_count: Any = ...
    target_table: Any = ...
    default_target: Any = ...

class CallImm(Structure):
    function_index: Any = ...

class CallIndirectImm(Structure):
    type_index: Any = ...
    reserved: Any = ...

class LocalVarXsImm(Structure):
    local_index: Any = ...

class GlobalVarXsImm(Structure):
    global_index: Any = ...

class MemoryImm(Structure):
    flags: Any = ...
    offset: Any = ...

class CurGrowMemImm(Structure):
    reserved: Any = ...

class I32ConstImm(Structure):
    value: Any = ...

class I64ConstImm(Structure):
    value: Any = ...

class F32ConstImm(Structure):
    value: Any = ...

class F64ConstImm(Structure):
    value: Any = ...
